### ISSUE TITLE
Implement Disconnect function to allow sending DISCONNECT_REQUEST to the Gateway

### ISSUE THREAD

**Issue by daBONDi** [usul27/pknx#2]
Implement Disconnect function to allow sending DISCONNECT_REQUEST to the Gateway:

Service Type Identifier: DISCONNECT_REQUEST = 0209h

Gatway should response with disconnect Message:

Service Type identifier: DISCONNECT_RESPONSE = 020Ah

**Comment by usul27** [comment]
Disconnect functionality has been implemented now.

**Comment by daBONDi** [comment]
Wireshark Says the KNXIP Disconnect Package is wrong!
![image](https://cloud.githubusercontent.com/assets/14858154/16209894/7399e1d6-3739-11e6-8e55-e92032348c1c.png)

**Comment by daBONDi** [comment]
Tunnel Server/Gateway trys a Disconnect from themself after some time:
![image](https://cloud.githubusercontent.com/assets/14858154/16209918/a02bce94-3739-11e6-94e4-ec38700e651c.png)

**Comment by daBONDi** [comment]
## File: knxip.ip
308: the self.hpai = is the **HPAI** of the Tunnel **Gateway**

330 disconnect() **you use the HPAI of the Tunnel Gateway**
_Should use HPAI of the Control Endpoint of the Client = SocketClient_

**Comment by daBONDi** [comment]
#6 Working for me now

**Comment by daBONDi** [comment]
Done
